[package]
name = "cachette"
version = "0.1.0"
edition = "2021"
authors = ["Luis Cardoso <luis@luiscardoso.dev>"]
description = "Cachette (hideout) is a Rust-based command-line interface (CLI) program that allows users to conceal secret messages in PNG image files using steganography."
readme = "README.md"
license = "MIT"
repository = "https://github.com/LuisCardosoOliveira/cachette"
keywords = ["steganography", "cli", "png", "hideout"]
categories = ["cli", "png"]

[profile.release]
panic = "abort"
lto = true # invokes the dark magic from LLVM's to link time optimizations (LTO)
codegen-units=1 # optimise code gen size
opt-level="s" # optimise for binary size

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.0"
base64 = "0.21.0"
clap = { version = "4.1.13", features = ["derive"] }
crc = "3.0.1"
rand = "0.8.5"
rpassword = "7.2.0"

[dev-dependencies]
assert_cmd = "2.0.10"
predicates = "3.0.2"
